### ISSUE TITLE
Repo cache refresh latency -> very stale stats

### ISSUE THREAD

**Issue by SpainTrain** [mnapoli/IsItMaintained#26] opened 2015-12-03 23:19 UTC
E.g. http://isitmaintained.com/project/SickRage/sickrage-issues

**Comment by mnapoli** [comment] 2015-12-04 09:49
Stats are cached and refreshed continuously. But since there are so many repositories registered I think the delay before a repository is refreshed is getting a little high :) I should try to look into what I can do. If you have ideas for optimizations in https://github.com/mnapoli/IsItMaintained/blob/master/src/Maintained/Application/Command/UpdateStatisticsCommand.php feel free to suggest.

**Comment by SpainTrain** [comment] 2015-12-04 15:48
I figured that was likely the underlying issue...  Where do you run this service (AWS, etc.)?

**Comment by mnapoli** [comment] 2015-12-04 15:52
A 5$ Digital Ocean droplet. But the main limit is the amount of HTTP queries to the GitHub API… IIRC there's a cron updating one package each minute (or maybe a little more than that): I don't want to hit GitHub's API limit.

Optimizations could be to find a way to make less API calls, or somehow detect if there have been changes since the last update, or do not update badges that are not fetched often… Or maybe easier: when a badge is generated, we check if the cache is older than (for example) a week and mark it to update (so that it's still asynchronous). Then each minute we update only the badges marked as "active". That will filter out *a lot* of unused badges/repositories. Those are random ideas.

**Comment by SpainTrain** [comment] 2015-12-04 16:24
I was asking more to see what queuing service(s) may be available than how much compute was available :grin:  This is a great use case for a task queue, but that's a lot of work to build "from scratch".

You can get the same functionality by prioritizing whatever list that cron job is pulling from.  I like the idea of checking for a max age when the badge is generated, then sending it to the top of the list.  If you only have 1440 updates per day, you want to be judicious with them :wink: .

**Comment by julmot** [comment] 2016-01-19 08:49
I can confirm that the status is never up2date. For example https://github.com/julmot/jmHighlight: It says the issue resolution time is 5 days. There were 5 counting issues within the last 6 months, all of them are solved within 1-3 days. Also if there is an open issue, the status badge of open issues will not change!

**Comment by lokenx** [comment] 2016-02-19 19:00
Any changes to this, or plans? Can we help out? Do we know the exact API limits of GitHub and where you're falling in between? Or load balancing between multiple machines to allow more frequent checks?

Also realized the repo owner and name are case sensitive. You'll get updated stats if I use all caps versus just lower case. I don't believe repo's are case sensitive so maybe this should be fixed.

**Comment by mnapoli** [comment] 2016-02-20 10:50
Hi all, I had another look today and it turned out the refresh command was stuck for about a month :( Sorry about that. I have restarted everything, cleared all the caches (please be gentle with the website for the next hours it already hit Github's API limit) so stats should be updated in the next hours (or even days - there is Cloudflare with a 1 day cache in front of the website). I have also changed the refresh rate to one repo every 3 minutes, hopefully that will be a little faster and still not hit the API limit… I'll try to keep a closer eye on the website in the future.

It could all be improved indeed, it just requires time :/ I guess what's needed is a simpler approach:

- drop the repository list/storage (it seems to be bugged anyway)
- everytime a repository's stats are queried, it should go in a queue
- the queue should not allow duplicates (so that a repository is not queued several times)
- a worker should process the queue to update the stats, and it should stop as soon as it hits the GitHub API limit (e.g. it should wait for 10 minutes)

That would ensure that badges/pages that are asked for are updated more frequently, and those that aren't don't take up resources.

**Comment by mnapoli** [comment] 2016-02-20 11:45
FYI I have added log monitoring (using Papertrail) and have changed the update frequency to once every minute. We'll see if this holds up!

**Closed** 2016-02-21 22:01 UTC
